apiVersion: operator.kyma-project.io/v1alpha1
kind: TransparentProxy
metadata:
  name: transparent-proxy
  namespace: sap-transp-proxy-system
spec:
  config:
    metrics:
      prometheus:
        enabled: true
    logging:
      level: info
    security:
      communication:
        internal:
          encryptionEnabled: true
    integration:
      destinationService:
        defaultInstanceName: ${SERVICE_INSTANCE_NAME}
        instances:
          - name: ${SERVICE_INSTANCE_NAME}
            serviceCredentials:
              secretKey: ${SECRET_KEY}
              secretName: ${SECRET_NAME}
              secretNamespace: ${SECRET_NAMESPACE}
      serviceMesh:
        istio:
          istio-injection: enabled
  deployment:
    resources:
      http:
        requests:
          cpu: 0.05
          memory: 192M
        limits:
          cpu: 0.05
          memory: 192M
      tcp:
        requests:
          cpu: 0.01
          memory: 64M
        limits:
          cpu: 0.01
          memory: 64M

